MTV 2.2 only Migrating virtual machines
kubev2v/forklift-documentation pull request #307
Opened 2022-03-24 16:19 UTC by RichardHoch

MTV 2.2 only. 

Same as the PR Remove "base64-encoded" from source provider instructions #299 https://github.com/konveyor/forklift-documentation/pull/299  **except for comment 1 in step 2**

2022-03-27 08:14 UTC, mguetta1 requested changes

2022-03-27 08:14 UTC, mguetta1 commented on documentation/modules/migrating-virtual-machines-cli.adoc
> +<3> {rhv-short} only: Specify the CA certificate of the {manager}. You can retrieve it at `https://<fqdn>/ovirt-engine/services/pki-resource?resource=ca-certificate&format=X509-PEM-CA`.
@RichardHoch please remove the "fqdn" change, it is handled in other PR & BZ

2022-03-27 08:14 UTC, mguetta1 commented on documentation/modules/migrating-virtual-machines-cli.adoc
> +<2> Specify the API end point URL, for example, `https://<fqdn>/sdk` for vSphere or `https://<fqdn>/ovirt-engine/api/` for {rhv-short}.
@RichardHoch please remove the "fqdn" change, it is handled in other PR & BZ

2022-03-27 12:05 UTC, RichardHoch commented
@mguetta1 -- Please approve this for MTV 2.2.  i removed the "fqdn" changes.

2022-03-28 05:51 UTC, mguetta1 approved these changes
Looks good to me

2023-11-12 09:48 UTC, closed without merging