Additional known issues for MTV 2.3.4
kubev2v/forklift-documentation pull request #346
Opened 2022-12-19 13:50 UTC by RichardHoch

MTV 2.3.4

Resolves https://issues.redhat.com/browse/MTV-436 by adding the following items to the "Known issues" section of the MTV 2/3 release notes: 

1. [Duplication of migration plan fails on storage mapping stage if source provider is RHV](https://bugzilla.redhat.com/show_bug.cgi?id=2143191) 
2. [Destination VMs in migrations with RHV souce clusters cannot boot because TPM data, such as source key dats, is not imported](https://issues.redhat.com/browse/MTV-435)

Preview:

2022-12-20 22:05 UTC, ahadas requested changes

2022-12-20 22:05 UTC, ahadas commented on documentation/modules/rn-2.3.adoc
> +.{rhv-short} destination VMs fail to boot if source keys are encrypted with TPM
the TPM part would be relevant as from the next version (2.4) so let's leave it out for now, what you wrote in jira better fits for 2.3.4: Migration of virtual machines with encrypted partitions fails during conversion

2022-12-20 22:05 UTC, ahadas commented on documentation/modules/rn-2.3.adoc
> +{project-short} does not use `virt-v2v` when it performs migrations from {rhv-short}. As a result any data in the source VM that is encrypted with TPM is not migrated to destination VMs. Therefore, a
this part would also be relevant as from 2.4, currently (2.3.4) we invoke virt-v2v for both vsphere and rhv - need to drop that sentense

2022-12-21 09:59 UTC, RichardHoch commented
@ahadas I made the change you requested. Please review the last two items in the Known issues and ask Igor to review the last one.

2023-01-09 07:32 UTC, RichardHoch commented
@ahadas Please review this PR again.

2023-01-09 08:12 UTC, ahadas commented on documentation/modules/rn-2.3.adoc
> +The problem occures for both vSphere amd {project-short} migrations.
amd -> and ?
{project-short} -> {rhv-short}?

2023-01-09 08:12 UTC, ahadas commented on documentation/modules/rn-2.3.adoc
> +.{project-short} 2.3.4 only: Duplication of migration plan fails in storage mapping stage if source provider is {rhv-short}.
we've seen it also in the network mapping stage, it would be better to mention both cases

2023-01-09 14:03 UTC, ahadas commented on documentation/modules/rn-2.3.adoc
> +.{project-short} 2.3.4 only: Duplication of migration plan fails in either the network stage or the storage mapping stage if source provider is {rhv-short}.
```suggestion
.{project-short} 2.3.4 only: Duplication of migration plan fails in either the network mapping stage or the storage mapping stage if source provider is {rhv-short}.
```

2023-01-09 14:04 UTC, ahadas commented
@RichardHoch one comment inside, besides that lgtm

2023-01-10 10:50 UTC, merged