OpenStack migration using the UI
kubev2v/forklift-documentation pull request #362
Opened 2023-03-29 14:41 UTC by RichardHoch

MTV 2.4

Partially resolves https://issues.redhat.com/browse/MTV-426 by describing how to define OpenStack source providers using the UI.

Also includes changes made to the procedures for defining other providers in the UI.

2023-03-29 16:02 UTC, sgratch reviewed
LGTM, few minor comments.

2023-03-30 10:04 UTC, ahadas commented on documentation/modules/adding-virt-provider.adoc
> +If both *URL* and *Service account token* are left blank, the local cluster provider is used.
```suggestion
If both *URL* and *Service account token* are left blank, the local openshift cluster is used.
```

2023-03-30 10:04 UTC, ahadas commented on documentation/modules/osh-adding-source-provider.adoc
> +* {manager} CA certificate or {manager} Apache CA certificate if the {manager} CA certificate was replaced by a third-party certificate on the Apache server
right, I also commented on that in #360

2023-03-30 16:41 UTC, RichardHoch commented on documentation/modules/osh-adding-source-provider.adoc
> +* {manager} CA certificate or {manager} Apache CA certificate if the {manager} CA certificate was replaced by a third-party certificate on the Apache server
Removing this prerequisite based on chat i had with Arik Thurs. afternoon. Let me know if anyone objects to me removing it.

2023-04-02 15:09 UTC, RichardHoch commented
@ahadas Please review again.

2023-04-13 15:00 UTC, RichardHoch commented
@ahadas @qiyann Please review this PR.

2023-04-13 15:27 UTC, ahadas commented on documentation/modules/adding-source-provider.adoc
> +*  {manager} CA certificate or {manager} Apache CA certificate if the {manager} CA certificate was replaced by a third-party certificate on the Apache server.
the phrasing in #354 (`{manager} CA certificate, unless it was replaced by a third-party certificate, in which case, specify the {manager} Apache CA certificate`) is better - need to make sure this change won't override it

2023-04-13 15:27 UTC, ahadas commented on documentation/modules/adding-virt-provider.adoc
> +If both *URL* and *Service account token* are left blank, the local OpenShift cluster is used.
```suggestion
If both *URL* and *Service account token* are left blank, the local {ocp} cluster is used.
```

2023-04-13 15:27 UTC, ahadas commented on documentation/modules/osh-adding-source-provider.adoc
> +. In the {project-short} web console, click *Providers*.
this needs to align with the changes in #357 (also above where `{project-short} web console` appears)

2023-04-13 15:27 UTC, ahadas commented on documentation/modules/osh-adding-source-provider.adoc
> +* *Domanin*:
```suggestion
* *Domain*:
```

2023-04-17 02:08 UTC, qiyuann requested changes

2023-04-17 02:08 UTC, qiyuann commented on documentation/modules/adding-virt-provider.adoc
>  * *URL*: Specify the API endpoint of the cluster.
```suggestion
* *Kubernetes API server URL*: Specify the API endpoint of the cluster.
```

2023-04-17 02:08 UTC, qiyuann commented on documentation/modules/osh-adding-source-provider.adoc
> +. Click *Add provider*.
```suggestion
. Click *Create Provider*.
```

2023-04-17 02:08 UTC, qiyuann commented on documentation/modules/osh-adding-source-provider.adoc
> +. Select *Red Hat OpenStack Platform* from the *Type* list.
```suggestion
. Select *Red Hat OpenStack Platform* from the *Provider type* list.
```

2023-04-17 02:08 UTC, qiyuann commented on documentation/modules/osh-adding-source-provider.adoc
> +* *Name*: Name to display in the list of providers
```suggestion
* *Provider name*: Name to display in the list of providers
```

2023-04-17 02:08 UTC, qiyuann commented on documentation/modules/osh-adding-source-provider.adoc
> +* *{osh} Identity (Keystone) URL*: {osh} Identity (Keystone) endpoint, for example, `http://controller:5000/v3`
```suggestion
* *{osh} Identity server URL*: {osh} Identity (Keystone) endpoint, for example, `http://controller:5000/v3`
```

2023-04-17 02:08 UTC, qiyuann commented on documentation/modules/osh-adding-source-provider.adoc
> +* *{osh} Identity (Keystone) username*: For example, `admin`
```suggestion
* *{osh} username*: For example, `admin`
```

2023-04-17 02:08 UTC, qiyuann commented on documentation/modules/osh-adding-source-provider.adoc
> +* *{osh} Identity (Keystone) password*:
```suggestion
* *{osh} password*:
```

2023-04-18 11:39 UTC, ahadas reviewed
minor comment ({osh} -> {osp}), other than that - lgtm

2023-04-18 11:39 UTC, ahadas commented on documentation/modules/osh-adding-source-provider.adoc
> +* *{osp} Identity server URL*: {osh} Identity (Keystone) endpoint, for example, `http://controller:5000/v3`
```suggestion
* *{osp} Identity server URL*: {osp} Identity (Keystone) endpoint, for example, `http://controller:5000/v3`
```
?

2023-04-18 11:46 UTC, qiyuann commented on documentation/modules/adding-source-provider.adoc
> +. Click *Create provider*.
```suggestion
. Click *Create Provider*.
```

2023-04-18 11:46 UTC, qiyuann commented on documentation/modules/adding-source-provider.adoc
> +. Select *Red Hat Virtualization* from the *Provider Type* list.
```suggestion
. Select *Red Hat Virtualization* from the *Provider type* list.
```

2023-04-18 11:46 UTC, qiyuann commented on documentation/modules/adding-virt-provider.adoc
> +. Click *Create provider*.
```suggestion
. Click *Create Provider*.
```

2023-04-18 12:07 UTC, RichardHoch commented
@ahadas Fixed it.
@qiyuann  I made the changes you suggested. Please check the PR again. Thanks!

2023-04-18 12:28 UTC, qiyuann approved these changes
LGTM

2023-04-18 14:40 UTC, merged