Telemetry
kubev2v/forklift-documentation pull request #584
Opened 2024-11-11 17:02 UTC by RichardHoch

MTV 2.8

Resolves https://issues.redhat.com/browse/MTV-1471 by adding a new section on MTV telemetry. 

Preview: https://file.corp.redhat.com/rhoch/telemetry/html-single/#telemetry

2024-11-11 22:50 UTC, nunzy1 commented
Hi Richard. Just a few comments. 

The preview doesn’t seem to agree with the file changes.  Also, this shows up in the preview:

"the following MTV usage data to improve the product: Data Data Data" or do we want to continue not mentioning it in customer-facing MTV documentation?
point out the data is anonymous and only used to make the product better and "proactive"."

For the bulleted points, I might do something like the following. (Please check our standards though.)

- Status: The number of migrations. Includes those that failed, succeeded, or were canceled.
- Provider: The number of migrations per provider. Includes Red Hat Virtualization, vSphere, OpenStack, OVA, and OpenShift Virtualization providers.
- Mode: The number of migrations by mode. Includes both cold and warm migrations.
- Target: The number of migrations by target. Includes targets that are local or remote. 
- Plan ID

I might shorten the sentence that follows:

Metrics are calculated every 10 seconds, and are reported per week, per month, and per year.

One note on “Plan ID” – I don’t see this mentioned anywhere else.  Is it completely obvious what it is?  If so, ok.  If not, can we say give some sort of description?

2024-11-12 17:01 UTC, RichardHoch commented
Thanks, @nunzy1 ! I made the changes you suggested.

2024-11-12 17:02 UTC, RichardHoch commented
@mnecas Please review this PR.

2024-12-13 12:20 UTC, fabiand reviewed
lgtm!

2024-12-15 08:34 UTC, RichardHoch commented
@jschuler Please review this PR. Thanks.

2024-12-17 12:59 UTC, fabiand approved these changes
lgtm!

2025-02-25 12:55 UTC, anarnold97 commented on documentation/modules/mtv-telemetry.adoc
> +Metrics are calculated every 10 seconds, and are reported per week, per month, and per year.
```suggestion
Metrics are calculated every 10 seconds and are reported per week, per month, and per year.
```

2025-02-25 18:06 UTC, RichardHoch commented
@anarnold97 I made the change you suggested. Please review this PR again. If good, please merge and publish. Thanks.

2025-03-04 13:23 UTC, anarnold97 commented on documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc
> +== Telemetry
Level 2 headers must have an ID. This could generate a build error in Pantheon.

2025-03-04 13:25 UTC, anarnold97 requested changes
Please ensure you follow basic documentation standards

2025-03-04 13:45 UTC, RichardHoch commented
@anarnold97 I made the changes you suggested. Please review this PR again. If good, please merge and publish. Thanks.

2025-03-04 14:51 UTC, anarnold97 approved these changes

2025-03-04 14:51 UTC, merged